Repository Flash1ce/10-4_le_chat_bot, pull requests merged in 2022-12, with the labels that each got.

#22 PR: Dev on master
  README.md
  commands/loadCommands.js
  commands/pingCommand.js
  package.json
Labels: publish

#24 PR: random number into dev
  commands/loadCommands.js
  commands/pingCommand.js
  commands/randomCommand.js
  deployCommands.js
  events/modalsEvents.js
Labels: request

#42 Fix Embed Missing
  commands/adminCommands/kick.js
  commands/adminCommands/timeout.js
  commands/adminCommands/unban.js
Labels: bug

#47 Random user online
  app.js
  commands/infosCommands/ping.js
  commands/loadCommands.js
  commands/randomCommands/random.js
  deployCommands.js
  events/interactionCreate.js
  includes/validations/randomCommands/randomValidators.js
  models/dbSetup.js
Labels: request

#45 Add status
  app.js
Labels: request

#51 Add database
  .env.exemple
  .gitignore
  app.js
  models/dbSetup.js
  models/scoreModel.js
  package-lock.json
  package.json
Labels: request

#52 Workflow setup
  .github/workflows/10-4-workflow-dev.yml
  .github/workflows/10-4-workflow-prod.yml
  appTest.js
  package-lock.json
  package.json
Labels: publish
